### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by hiteshBhatia** [aws/aws-week-in-review#275]
In Section "New & Notable Open Source" in "_AWS Week in Review – October 10, 2016_" couple of links are broken links
- Links to node-aws-sqs-redriver is broken.
- Link to awsm incorrect.

**Comment by rjhintz** [comment]
Link for [node-aws-sqs-redriver](https://github.com/Springworks/node-aws-sqs-redriver)

I'm not sure of the proper link for `awsm`. It may be [https://github.com/awsm-org/awsm](awsm-org/awsm)

There's another issue, though, in that, as of Merge 269, commit 5723484, I don't see any entries at all in the New/Notable Open Source section. and there are 10 or so in the actual Week In Review as published.

I went back a few commits from @jeffbarr and didn't see any entries in this section.

**Comment by jeffbarr** [comment]
I fixed the broken link to awsm and will check on node-aws-sqs-redriver now (fixed it). I generally copy the HTML from GitHub to WordPress on Monday morning and make final edits there. I am planning to add additional rigor, documentation, and a clear schedule soon. Thanks for your patience!

**Comment by rjhintz** [comment]
@jeffbarr Thanks for clarifying the final production process. 

There's an obvious issue with getting out of sync with what we see here, as with the missing entries in the Open Source section that I mentioned above. Since the edit process is evolving, I'm certainly fine with going with your judgment.
